if: branch = master

language: go
go:
  - 1.11.x

addons:
  ssh_known_hosts: johnjago.com

script:
  - mkdir -p dist/blog/
  - cd src/blog/
  - ../../bin/hugo && mv public/* ../../dist/blog/ && cd ..
  - rsync -av --exclude=blog/ --exclude=favicon.png . ../dist/
  - cd ..

before_deploy:
  - openssl aes-256-cbc -K $encrypted_829f045482e5_key -iv $encrypted_829f045482e5_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  skip_cleanup: true
  provider: script
  script: rsync -azvP --delete --exclude=/deformat --exclude=/musearch dist/ $USER@johnjago.com:$WWW/
