language: generic
if: branch = master

addons:
  ssh_known_hosts: johnjago.com

install: true

script:
  - mkdir -p dist/blog/
  - cd src/blog/ && hugo && mv public/* ../../dist/blog/ && cd ..
  - rsync -av --exclude=blog/ --exclude=favicon.png . ../dist/

before_deploy:
  - openssl aes-256-cbc -K $encrypted_829f045482e5_key -iv $encrypted_829f045482e5_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  script: rsync --dry-run -azvP --delete dist/ $USER@johnjago.com:$WWW/
