baseURL = "https://johnjago.com/blog/"
languageCode = "en-us"
title = "John’s Software Blog"
theme = "journal"

[author]
  name = "John Jago"
  homepage = "https://johnjago.com"

[params]
  description = "Sharing what I learn about Linux, backend development, and the software industry."
  tagline = "Linux, backend development, and other musings"

[[menu.main]]
  name = "Now"
  url="https://johnjago.com"
[[menu.main]]
  name = "About"
  url = "about/"
